const data = {
  pieData: [
    { item: "事例一", count: 40, percent: 0.4 },
    { item: "事例二", count: 21, percent: 0.21 },
    { item: "事例三", count: 17, percent: 0.17 },
    {
      item: "事例四xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxYYYY",
      count: 13,
      percent: 0.13,
    },
    { item: "事例五", count: 9, percent: 0.09 },
  ],
  radarData: [
    { item: "Design", a: 70, b: 30 },
    { item: "Development", a: 60, b: 70 },
    { item: "Marketing", a: 50, b: 60 },
    { item: "Users", a: 40, b: 50 },
    { item: "Test", a: 60, b: 70 },
    { item: "Language", a: 70, b: 50 },
    { item: "Technology", a: 50, b: 40 },
    { item: "Support", a: 30, b: 40 },
    { item: "Sales", a: 60, b: 40 },
    { item: "UX", a: 50, b: 60 },
  ],
  column: [
    { year: "1951 年", sales: 38 },
    { year: "1952 年", sales: 52 },
    { year: "1956 年", sales: 61 },
    { year: "1957 年", sales: 45 },
    { year: "1958 年", sales: 48 },
    { year: "1959 年", sales: 38 },
    { year: "1960 年", sales: 38 },
    { year: "1962 年", sales: 38 },
  ],
  groub: [
    { name: "London", month: "Jan.", avgRainfall: 18.9 },
    { name: "London", month: "Feb.", avgRainfall: 28.8 },
    { name: "London", month: "Mar.", avgRainfall: 39.3 },
    { name: "London", month: "Apr.", avgRainfall: 20.4 },
    { name: "London", month: "May", avgRainfall: 47 },
    { name: "London", month: "Jun.", avgRainfall: 20.3 },
    { name: "London", month: "Jul.", avgRainfall: 24 },
    { name: "London", month: "Aug.", avgRainfall: null },
    { name: "Paris", month: "Jan.", avgRainfall: 19.9 },
    { name: "Paris", month: "Feb.", avgRainfall: 28.8 },
    { name: "Paris", month: "Mar.", avgRainfall: 29.3 },
    { name: "Paris", month: "Apr.", avgRainfall: null },
    { name: "Paris", month: "May", avgRainfall: 67 },
    { name: "Paris", month: "Jun.", avgRainfall: null },
    { name: "Paris", month: "Jul.", avgRainfall: 23 },
    { name: "Paris", month: "Aug.", avgRainfall: null },
    { name: "Berlin", month: "Jan.", avgRainfall: 12.4 },
    { name: "Berlin", month: "Feb.", avgRainfall: 23.2 },
    { name: "Berlin", month: "Mar.", avgRainfall: 34.5 },
    { name: "Berlin", month: "Apr.", avgRainfall: null },
    { name: "Berlin", month: "May", avgRainfall: 52.6 },
    { name: "Berlin", month: "Jun.", avgRainfall: 35.5 },
    { name: "Berlin", month: "Jul.", avgRainfall: 37.4 },
    { name: "Berlin", month: "Aug.", avgRainfall: 42.4 },
  ],
};

export default data;
